version: '3.9'
services:
  postgres:
    profiles: ["test", "development"]
    image: postgres:14.5
    container_name: orderSystem
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      TZ: Asia/Seoul
    ports:
      - ${DOCKER_PORT}